import { Inter,Source_Sans_3,Roboto } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from './Providers'
import User from './models/user'
import Header from './Components/Header'

export const dynamic = 'force-dynamic'
export const revalidate = 0

const inter = Inter({
  subsets: ['latin'], 
  display: 'block'  
})

const roboto = Roboto({
  subsets: ['latin'], 
  display: 'block',  
  weight:['100','300']
})

const sourceSans = Source_Sans_3({
  subsets: ['latin'],
  display: 'block',
  variable: '--font-sourceSans',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
    <NextAuthProvider>
      <body className={ ` ${sourceSans.className}`}>
          <Header/>
          <div className='ml-20'>
              {children}
          </div>
          

        </body>
        </NextAuthProvider>
    </html>
  )
}
